# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dogecon
email: carpelunam@gmail.com
url: "http://dogecon.fun"
description: Information on Dogecon Vancouver 2018

# the subpath of your site, e.g. /blog
baseurl: ""
twitter_username: ""
github_username:  ""
linkedin_username: ""
linkedin_url: ""
markdown: kramdown
plugins:
  - jekyll-redirect-from
